-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTtWLcqE33r1+1J8x
AavoDErVgMeklhTWBqTG2/2xHHmgCgYIKoZIzj0DAQehRANCAAThwZJYwiY17HMj
6CrW2/zuBDQG8rZ3IcGmufiPuOVGJxQtWJhm7zQQR9CQOMgPKoQg3tkCnpMfzIXS
cCVgDVZ+
-----END PRIVATE KEY-----